<?php

namespace MlankaTech\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionRepository extends EntityRepository
{
    /**
     * Get condition
     *
     * @param string $condition
     * @return MlankaTechAppBundle:Condition
     */
    public function getCondition($condition)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.name = :condition_name')
            ->setParameter('condition_name', $condition);

        return $qb->getQuery()->getSingleResult();
    }
}