<?php

namespace MlankaTech\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * MotorCoachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotorCoachRepository extends EntityRepository
{
    /**
     * Get query of all train types
     *
     * @param array $options
     * @return Query
     */
    public function getAllQueryList($options)
    {

        $defaultOptions = array(
            'search' => '',
            'filterBy' => '',
            'sort' => 'm.id',
            'direction' => 'desc',
            'show' => 10,
        );

        foreach ($options as $key => $values) {
            if (!$values) {
                $options[$key] = $defaultOptions[$key];
            }
        }

        $qb = $this->createQueryBuilder('m')->select('m')
            ->innerJoin('m.status','s')
            ->innerJoin('m.condition','c');

        // search
        if ($options['search']) {
            if ($options['search'] != "") {
                $qb->andWhere($qb->expr()->orx(
                    $qb->expr()->like('m.unit', $qb->expr()->literal('%' . $options['search'] . '%'))
                ));
            }
        }

        $qb->orderBy($options['sort'], $options['direction']);
        return $qb->getQuery();
    }
}