<?php

namespace MlankaTech\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * MotorCoachTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotorCoachTransactionRepository extends EntityRepository
{
    /**
     * Get query of motor coach transactions by motor coach
     *
     * @param $motorCoach
     * @param int $limit
     * @return \Doctrine\ORM\Query
     */
    public function getByMotorCoach($motorCoach,$limit = 10)
    {

        $qb = $this->createQueryBuilder('m')->select('m')
            ->where('m.motorCoach = :motorCoach')
            ->setParameter('motorCoach', $motorCoach)
            ->setMaxResults($limit);


        $qb->orderBy('m.createdAt', "DESC");
        return $qb->getQuery()->execute();
    }

    /**
     * Get recent transactions per train
     *
     * @param int $limit
     * @return \Doctrine\ORM\Query
     */
    public function getLatestPerTrain($limit = 10)
    {

        $qb = $this->createQueryBuilder('m')->select('m')
            ->distinct(true)
            ->setMaxResults($limit);


        $qb->orderBy('m.createdAt', "DESC");
        return $qb->getQuery()->execute();
    }
}
