<?php

namespace MlankaTech\AppBundle\Entity\Repository;

/**
 * TrainTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
