<?php

namespace MlankaTech\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserGroupRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupRepository extends EntityRepository
{
    /**
     * Get group.
     *
     * @param string $name
     *
     * @return MlankaTechAppBundle:UserGroup
     */
    public function getType($name)
    {
        $qb = $this->createQueryBuilder('u')
            ->where('u.name = :group_name')
            ->setParameter('group_name', $name);

        return $qb->getQuery()->getSingleResult();
    }
}