fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

mlanka_tech_app_security:
    resource: "@MlankaTechAppBundle/Resources/config/routing.security.yml"
    prefix:   /

mlanka_tech_app_dashboard:
    resource: "@MlankaTechAppBundle/Resources/config/routing.dashboard.yml"
    prefix:   /

mlanka_tech_app_user:
    resource: "@MlankaTechAppBundle/Resources/config/routing.user.yml"
    prefix:   /

mlanka_tech_app_settings_train_types:
    resource: "@MlankaTechAppBundle/Resources/config/routing.train.types.yml"
    prefix:   /

mlanka_tech_app_settings_motor_coach_types:
    resource: "@MlankaTechAppBundle/Resources/config/routing.motor.coach.types.yml"
    prefix:   /

mlanka_tech_app_motor_coach:
    resource: "@MlankaTechAppBundle/Resources/config/routing.motor.coach.yml"
    prefix:   /

mlanka_tech_app_train:
    resource: "@MlankaTechAppBundle/Resources/config/routing.train.yml"
    prefix:   /
