fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

mlanka_tech_app_security:
    resource: "@MlankaTechAppBundle/Resources/config/routing.security.yml"
    prefix:   /

mlanka_tech_app_dashboard:
    resource: "@MlankaTechAppBundle/Resources/config/routing.dashboard.yml"
    prefix:   /
