_security_login:
    path:  /login.{_format}
    defaults: { _controller: MlankaTechAppBundle:Security:login , _format: html}
    schemes:  [http]
    methods:  [GET, POST]
    requirements:
        _format:  html

_security_check:
    path:  /login_check
    schemes:  [http]
    methods:  [GET, POST]

_security_logout:
    pattern:  /logout.html

_homepage:
    path:  /
    defaults: { _controller: MlankaTechAppBundle:Security:login , _format: html}
    schemes:  [http]
    methods:  [GET, POST]
    requirements:
        _format:  html