mlankatech_app.app_broadcast:
    path:  /api/broadcast
    defaults: { _controller: MlankaTechAppBundle:Api:broadcast , _format: html}
    schemes:  [http]
    methods:  [GET]
    requirements:
        _format:  json
