services:
    security.authentication.success_handler:
        class: MlankaTech\AppBundle\Handler\Security\AuthenticationSuccessHandler
        arguments: [@security.http_utils, {} , @service_container]
        tags:
            - { name: 'monolog.logger', channel: 'security'}
